name: CI

on:
  push:
    branches:
      - main

jobs:
  check-merge-conflict:
    runs-on: alpine-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Check for merge conflicts
      run: git merge-base --is-ancestor HEAD $(git merge-base main HEAD) || exit 1

  other-ci-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add other steps for your CI checks here, such as running tests, linting, etc.

